### PR TITLE
Add rsk

### PR DESCRIPTION
**Pull request by oscarguindzberg**

### CODE REVIEW

**Comment by schildbach** [comment]
Does RSK actually want to be listed? And out of curiosity, what are they using bitcoinj for?

**Comment by oscarguindzberg** [comment]
RSK is a merge-mined bitcoin sidechain written in java.
It uses bitcoinj to :
- validate merge-mining data in btc blocks
- checking SPV proofs of btc->rsk txs
- builing rsk->btc txs

RSK uses bitcoinj on open-source repositories.
See
https://github.com/rsksmart/bitcoinj-thin
https://github.com/rsksmart/rskj/search?q=bitcoinj&unscoped_q=bitcoinj

@aeidelman @SergioDemianLerner

**Comment by SergioDemianLerner** [comment]
True.

**Comment by schildbach** [comment]
Ok thanks, merged!

**Pull request closed without merging**
